version: "3.3"

services:

  node-rk:
    image: node:6.10
    container_name: rk-node
    volumes:
      - ./app:/var/www/rk-dis
    working_dir: /var/www/rk-dis
    tty: true

  php-rk:
    container_name: rk-php
    build: docker/php
    restart: always
    networks:
      - rk
    volumes:
      - .:/var/www/rk-dis

  nginx-rk:
    container_name: rk-nginx
    build: docker/nginx
    restart: always
    volumes:
      - .:/var/www/rk-dis
    networks:
      - rk
    ports:
      - 8080:80

  mysql-rk:
    container_name: rk-mysql
    image: mariadb:10.3
    restart: always
    networks:
      - rk
    ports:
      - 3301:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"

networks:
  rk:
